spring:
  application:
    name: my_super_agent
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://rm-cn-rp649mien0002nco.rwlb.rds.aliyuncs.com/my_agent
    username: lyx
    password: ${spring.datasource.password}
  ai:
    dashscope:
      api-key: ${spring.ai.dashscope.api-key}
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json

#    mcp:
#      client:
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
#    vectorstore:
#      pgvector:
#        index-type: hnsw
#        dimensions: 1024
#        distance-type: cosine_distance
#        max-document-batch-size: 1000


# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    version: 3.1.0
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.my_super_agent.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn


server:
  port: 8123
  servlet:
    context-path: /api


searchApi:
  apiKey: ${searchApi.apiKey}


